<table cellpadding=2 cellspacing=1 border=0 align="right">
<tr>
	<td align="right" width="25%">
	<font face="Tahoma, Arial, Helvetica" size=1>legend:</font></td>
	<td align="center" width="25%" bgcolor="#9999ff">
	<font face="Tahoma, Arial, Helvetica" size=1><nobr>15' session</nobr></font></td>
	<td align="center" width="25%" bgcolor="#99ff99">
	<font face="Tahoma, Arial, Helvetica" size=1><nobr>30' session</nobr></font></td>
	<td align="center" width="25%" bgcolor="#ff9999">
	<font face="Tahoma, Arial, Helvetica" size=1><nobr>mock interview</nobr></font></td>
</table>